version: "2.4"

services:
  app2-influxdb:
    image: influxdb:2-alpine
    restart: unless-stopped
    mem_limit: 1400m
    logging:
      options:
        max-size: "10m"
        max-file: "2"
      driver: json-file
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    networks:
      - proxy-redirect

  app2-telegraf:
    image: telegraf:1.34-alpine
    restart: unless-stopped
    mem_limit: 500m
    logging:
      options:
        max-size: "10m"
        max-file: "2"
      driver: json-file
    depends_on:
      - app2-influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
    networks:
      - proxy-redirect

networks:
  proxy-redirect:
    external:
      name: proxy-redirect
    driver: bridge
    

volumes:
  influxdb2-data:
  influxdb2-config:
