version: "2.4"

services:
  app2-influxdb:
    extends:
      file: ./base.yml
      service: app2-base
    image: influxdb:2-alpine
    mem_limit: 1400m
    ports:
      - 8086:8086
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2

  app2-data-collector:
    extends:
      file: ./base.yml
      service: app2-base
    image: voigtlandera/data-collector:v0.0.4
    build: ./data-collector
    mem_limit: 1000m
    depends_on:
      - app2-influxdb

#  app2-analyzer:
#    extends:
#      file: ./base.yml
#      service: app2-base
#    build: ./analyzer
#    image: analyzer:v0.0.1
#    mem_limit: 1000m
#    depends_on:
#      - app2-influxdb


networks:
  proxy-redirect:
    external:
      name: proxy-redirect
    driver: bridge
    

volumes:
  influxdb2-data:
  influxdb2-config:
